### ISSUE TITLE
Configurable bit position per enum

### ISSUE THREAD

**Issue by iamtommo** [claudemartin/enum-bit-set#1]
Nice project you have here.

The EnumBitSet would be perfect for my use case, except the the fact that for each enum, the bit position must be configurable and cannot rely on the enum ordinal.

Any chance this may be introduced? Otherwise a PR may be in order.

**Comment by claudemartin** [comment]
this is just a side project of mine. I'm now woring on migrating to Java 10 and Junit 5. Maybe I'll add the possibility to override the value used in enums.

**Comment by claudemartin** [comment]
This would not be possible. The whole point is that EnumBitSet uses enums. It uses EnumSet internally. 
So just use a GeneralDomainBitSet:
https://gist.github.com/claudemartin/7f7da857c4530050be55917e44caafca
